#!/bin/bash

# 初始化总和为0
sum=0

# 初始化参数列表字符串
params=""

# 遍历所有的命令行参数
for param in "$@"
do
    # 将参数加到总和中
    sum=$((sum + param))

    # 将参数加到参数列表字符串中
    params="$params $param"
done

# 输出总和
echo "sum$params : $sum"
