#!/bin/bash
# passing parameters to a function
function addem {
if [ $# -eq 0 ] || [ $# -gt 2 ]             #参数数量=0， OR ， >2
then
	echo -1                                  #函数 返回 -1
elif [ $# -eq 1 ]              		#参数数量=1
then
	echo $[ $1 + $1 ]		 #函数 参数1  + 参数1
else
	echo $[ $1 + $2 ]  		 #函数 返回 二个参数的和
fi
}

